name: Build JSP

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check out CLDR
      uses: actions/checkout@v2
      with:
        repository: unicode-org/cldr
        path: cldr
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build all with Maven
      run: >
        mvn -s .github/workflows/mvn-settings.xml -B compile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # TODO: move this DOWN after JSPs once it works
    - name: Run unicodetools tests
      run: >
        mvn -s .github/workflows/mvn-settings.xml -B test --file=unicodetools/pom.xml -DCLDR_DIR=${CLDR_DIR} -T 1C -Dparallel=classes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLDR_DIR: ${{ secrets.GITHUB_WORKSPACE }}/cldr
    - name: Package JSPs
      run: >
        mvn -s .github/workflows/mvn-settings.xml -B -pl UnicodeJsps install package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload UnicodeJsps.war
      uses: actions/upload-artifact@v2
      with:
        name: UnicodeJsps
        path: UnicodeJsps/target/UnicodeJsps.war
    - name: build docker image
      run: cd UnicodeJsps && docker build .

