name: build.md

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:

  # Only run 1 or 2 commands for in-source build instructions, just to demonstrate
  # what translating between an out-of-source build and an in-source build would
  # look like. Rely on out-of-source build steps as the canonical way to
  # execute tools in CI and write corresponding documentation.
  in-source-build:
    name: In-source Instructions (Examples)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Unicode Tools
        uses: actions/checkout@v2
      - name: Check out CLDR
        uses: actions/checkout@v2
        with:
          repository: unicode-org/cldr
          path: cldr
      - name: Move CLDR working copy to be sibling of Unicode Tools
        run: |
          mv cldr ..
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up in-source output dir
        run: |
          mkdir -p Generated/BIN
      - name: Initialize Maven settings for all Maven commands
        run: mvn -s .github/workflows/mvn-settings.xml -B compile install -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run command - Build and Test
        run: MAVEN_OPTS="-ea" mvn -s .github/workflows/mvn-settings.xml package -DCLDR_DIR=$(cd ../cldr ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd Generated; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run command - Make Unicode Files
        run: MAVEN_OPTS="-ea" mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.text.UCD.Main"  -Dexec.args="version 15.0.0 build MakeUnicodeFiles"  -pl unicodetools  -DCLDR_DIR=$(cd ../cldr ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd Generated; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  out-of-source-build:
    name: Out-of-source Instructions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Unicode Tools
        uses: actions/checkout@v2
        with:
          repository: unicode-org/unicodetools
          path: unicodetools/mine/src
      - name: Checkout CLDR
        uses: actions/checkout@v2
        with:
          repository: unicode-org/cldr
          path: cldr/mine/src
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up out-of-source output dir
        run: |
          mkdir -p unicodetools/mine/Generated/BIN
      - name: Initialize Maven settings for all Maven commands
        run: |
          cd unicodetools/mine/src
          mvn -s .github/workflows/mvn-settings.xml -B compile install -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run command - Build and Test
        run: |
          cd unicodetools/mine/src
          MAVEN_OPTS="-ea" mvn -s .github/workflows/mvn-settings.xml package -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run command - Make Unicode Files
        run: |
          cd unicodetools/mine/src
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.text.UCD.Main"  -Dexec.args="version 15.0.0 build MakeUnicodeFiles"  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/unicode-org/unicodetools/blob/main/docs/emoji/aac.md#aacorderjava
      - name: Run command - AAC Order
        run: |
          cd unicodetools/mine/src
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.tools.AacOrder"  -Dexec.args="version 15.0.0 build MakeUnicodeFiles"  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/unicode-org/unicodetools/blob/main/docs/uca/index.md#tools--tests
      # Note: Not running desuffixucd.py in UCA jobs because no version numbers detected in data file names
      - name: Run command - UCA - collation validity log
        run: |
          cd unicodetools/mine/src
          # invoke main() in class ...UCA.Main
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.text.UCA.Main"  -Dexec.args="writeCollationValidityLog"  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
          # check for output file
          compgen -G "../Generated/UCA/*/CheckCollationValidity.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # TODO: file issue to uncomment, debug errors, and fix?
      # - name: Run command - UCA - for CLDR & ICU
      #   run: |
      #     cd unicodetools/mine/src
      #     # invoke main() in class ...UCA.Main
      #     mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.text.UCA.Main"  -Dexec.args="ICU"  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/unicode-org/unicodetools/blob/main/docs/idna.md
      - name: Run command - IDNA
        run: |
          cd unicodetools/mine/src
          # Confirm that the directory for the bin files exists
          compgen -G "../Generated/BIN"
          # "Delete all the bin files" as per instructions
          rm -rf ../Generated/BIN/*
          # run GenerateIdna
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.idna.GenerateIdna"  -Dexec.args=""  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/unicode-org/unicodetools/blob/main/docs/idna.md
      - name: Run command - Generate IDNA Test
        run: |
          cd unicodetools/mine/src
          # Confirm that the directory for the bin files exists
          compgen -G "../Generated/BIN"
          # "Delete all the bin files" as per instructions
          rm -rf ../Generated/BIN/*
          # run GenerateIdnaTest
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.idna.GenerateIdnaTest"  -Dexec.args=""  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/unicode-org/unicodetools/blob/main/docs/newunicodeproperties.md#run-generateenumsjava
      - name: Run command - Generate Enums Test
        run: |
          cd unicodetools/mine/src
          # run GenerateEnums
          mvn -s .github/workflows/mvn-settings.xml exec:java -Dexec.mainClass="org.unicode.props.GenerateEnums"  -Dexec.args=""  -pl unicodetools  -DCLDR_DIR=$(cd ../../../cldr/mine/src ; pwd)  -DUNICODETOOLS_GEN_DIR=$(cd ../Generated ; pwd)  -DUNICODETOOLS_REPO_DIR=$(pwd)  -DUVERSION=15.0.0
          # TODO(#100) Get rid of need for fake version 13.1 of Unicode enum val
          # Fail if we haven't committed changes from Generate Enums, but make exception for fake Unicode version hack (#100)
          echo "Check if GenerateEnums output has been committed to repo"
          git diff --compact-summary --exit-code
          if [ $? -eq 0 ]; then
            echo "Success: Any output from GenerateEnums has already been committed."
            echo "exit 0"
          else
            names=`git diff --name-status | awk '{print $2;}'`
            if [[ "$names" == "unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java" ]]; then
              gitdiffstat=`git diff --stat | tail -n 1`
              if [[ "$gitdiffstat" = "1 file changed, 1 insertion(+), 1 deletion(-)" ]]; then
                git diff | grep 'V13_1("13.1")'
                if [ $? -eq 0 ]; then
                  echo "Inferred: Only non-committed change after GenerateEnums is temporary V13_1 hack (issue #100)"
                  echo "Check passed."
                  echo "exit 0"
                fi
              fi
            fi
            echo "Failure: GenerateEnums has changed that need to be committed."
            echo "exit 1"
          fi
          # TODO(#100): Note: when running locally on a clean checkout, this command
          # leaves a change in UcdPropertyValues.java by not preserving the comment 
          # about the fake Unicode version 13.1.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

